### ISSUE TITLE
[BUG] Payment Declined for Security Reasons

### ISSUE THREAD

**Issue by ak-singla** [PatilShreyas/EasyUpiPayment-Android#109]
![D71589BA-0DB9-4E42-9976-D4E7492ACB3F](https://user-images.githubusercontent.com/6893693/113376403-47d9e200-938f-11eb-8a7a-e45a0dd4a37a.jpeg)

Payment declined.

For security reasons, you are not allowed to send money from your bank for this payment. 

You don’t have to enter your UPI pin to receive money/cash back.

**Comment by mathantechsolutions** [comment]
Please confirm if you are using merchant upi id for making payments

**Comment by PatilShreyas** [comment]
As @mathantechsolutions mentioned, see [docs](https://patilshreyas.github.io/EasyUpiPayment-Android/#/?id=introduction) and check whether you're performing transaction against a valid merchant/business account.

**Comment by VIkash2601** [comment]
Hi, @PatilShreyas I'm using a Merchant Account as Payee for the transaction but still facing the same issue as tagged here.

**Comment by jayantamahato** [comment]
> Hi, @PatilShreyas I'm using a Merchant Account as Payee for the transaction but still facing the same issue as tagged here.

did you solve this proble?
I'm facing same problem for flutter
