### ISSUE TITLE
App not found exception in android 11

### ISSUE THREAD

**Issue by AshishKumarYadav** [PatilShreyas/EasyUpiPayment-Android#112]
This is the exception I'm facing

W/System.err: dev.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app with package name 'com.phonepe.app' exists on this device to perform this transaction.

**Comment by PatilShreyas** [comment]
This exception comes up when UPI applications do not exist on your device. Do you have them on your device?

**Comment by AshishKumarYadav** [comment]
Yes I have the UPI apps like Gpay, PhonePe, Paytm.

I tried all the PAYMENT_TYPE.ALL/PAYMENT_TYPE.GPAY/PAYMENT_TYPE.PHONE_PE none is working.

**Comment by AshishKumarYadav** [comment]
Even your demo app is not working in my device. Getting ANR.

**Comment by supertramp09** [comment]
Same Here. Getting the exception even though I have mutliple UPI apps installed.

**Comment by mathantechsolutions** [comment]
Same here i am also getting no upi apps found but i have installed gpay,phonepe and paytm . i think this error maybe android 11 issue we have to add query tag in manifest but i don't know exactly

**Comment by PatilShreyas** [comment]
Thanks for reporting this issue. Looks like this is happening for devices having Android 11. Currently, I don't have any device having Android 11 to test this change. I've tried to fix this change and attached APK here 👇🏻.

[***Download Sample APK***](https://github.com/PatilShreyas/EasyUpiPayment-Android/raw/v3.0.3-dev/app/app-debug.apk)

It's my humble request to test the attached APK and please let me know if it works as expected. If it works, I'll be happy to release the new version `v3.0.3`.

**Comment by amitav13** [comment]
I was able to see options for a upi app now. But the txn didn't go through - might be wrong input on my end.

**Comment by PatilShreyas** [comment]
Was this on Android 11 @amitav13?

**Comment by amitav13** [comment]
> Was this on Android 11 @amitav13?

Yep! Galaxy s20+, if that helps.

**Comment by PatilShreyas** [comment]
Try sending money to the business account, it'll be successful. For a normal account, it doesn't work.

**Comment by amitav13** [comment]
> Try sending money to the business account, it'll be successful. For a normal account, it doesn't work.

Ah I didn't know there was a distinction for a business account. Is there a "test" public business account? Or is it possible to make one myself for testing?

**Comment by PatilShreyas** [comment]
Create any business account using apps like GPay Business, PhonePe Business
App, Paytm Business App.

**Comment by PatilShreyas** [comment]
Thanks, this has been fixed in the latest release `v3.0.3`.

@amitav13 Really appreciate your time in helping me in testing it on the device. Thank you so much.

**Comment by viratsoft** [comment]
Not work in Android 11 (S10+) app crashed with "No upi app found, Please install to process". i have already have 3 upi app.

**Comment by AbhinavChauhan97** [comment]
it is still crashing on my android 10 in v3.0.3

**Comment by ramank24** [comment]
When I am overriding function onAppNotFound() as :
override fun onAppNotFound(transactionDetails: TransactionDetails) {
}

It giving compilation error : 'onAppNotFound' overrides nothing

Kindly help.

**Comment by ramank24** [comment]
One more point I would like to mention regarding integration of EasyUpiPayment in my app is that I am doing this inside the fragment. My App flow is like:

1. User click membership button then I call a fragment
2. Inside this fragment then I invoke EasyUpiPayment api

So point is whether this approach Ok?
