### ISSUE TITLE
Showin "Cancelled" toast in some devices while click pay button , and after it returned to home page .

### ISSUE THREAD

**Issue by basheerbsr79** [PatilShreyas/EasyUpiPayment-Android#113]
All UPI Paymnent failed in some devices Like Poco F1. 

After click pay button showing a toast "Cancelled" and app will return to the payment page .
Phone Specification photo and and its video is attached ,

https://user-images.githubusercontent.com/74948893/119965198-a4403300-bfc7-11eb-880f-f838d3064c7d.mp4

![WhatsApp Image 2021-05-23 at 9 52 44 PM](https://user-images.githubusercontent.com/74948893/119934892-2b7baf80-bfa4-11eb-8407-6e18c8c46304.jpeg)

**Comment by PatilShreyas** [comment]
@basheerbsr79 Thanks for reporting this. But if payment is cancelled from UPI apps and let's say payment is declined then UPI app is closed and library doesn't gets response from UPI app then it's considered as a ***Cancelled*** payment. Also, I think then this is correct. Right>

**Comment by basheerbsr79** [comment]
> @basheerbsr79 Thanks for reporting this. But if payment is cancelled from UPI apps and let's say payment is declined then UPI app is closed and library doesn't gets response from UPI app then it's considered as a _**Cancelled**_ payment. Also, I think then this is correct. Right>

@PatilShreyas Thanks for your response. but the same UPI working on many phone . and the payment is automatically cancelled by the phone . what is the reason for some device has only the problem..?

**Comment by PatilShreyas** [comment]
The payment information is also same across all the devices?

**Comment by basheerbsr79** [comment]
@PatilShreyas yes

**Comment by basheerbsr79** [comment]
@PatilShreyas yes . the same details is working fine with Mi 10 i Device 

![WhatsApp Image 2021-05-28 at 4 42 14 PM](https://user-images.githubusercontent.com/74948893/119975630-b6c06980-bfd3-11eb-95c2-4c18e0f08205.jpeg)


https://user-images.githubusercontent.com/74948893/119975440-7bbe3600-bfd3-11eb-8c5f-f3ade58a6d88.mp4

**Comment by PatilShreyas** [comment]
Yes, so this is expected behaviour. When the UPI app rejects payment it's considered a cancelled transaction. I saw you provided merchant code as `1` so that's why UPI app is rejecting payment.

**Comment by basheerbsr79** [comment]
> Yes, so this is expected behaviour. When the UPI app rejects payment it's considered a cancelled transaction. I saw you provided merchant code as `1` so that's why UPI app is rejecting payment.

Could you please let know more about the merchant code . actually i don't know what is the merchant code
