### ISSUE TITLE
Unable to Pay to UPI id

### ISSUE THREAD

**Issue by sangram-chavan** [PatilShreyas/EasyUpiPayment-Android#114]
Entered all details correctly

Reason for Failure BHIM App show

"RISK THRESHOLD EXCEEDED"

response code : U16

Same tried directly from UPI I'd I works

**Comment by PatilShreyas** [comment]
Some UPI apps fail on payment processed through intents. So this is something where the library can't do anything. Payment should be done for business UPI account and it works for it.
