### ISSUE TITLE
I have solutions - -----GPAY is working When you register bank UPI ID like --- @dbs , @hdfc ok thanks me leter 

### ISSUE THREAD

**Issue by govindowlok0** [PatilShreyas/EasyUpiPayment-Android#124]
Write information about Bug/Feature Request here

**Comment by PatilShreyas** [comment]
[Discussions](https://github.com/PatilShreyas/EasyUpiPayment-Android/discussions) is the proper place to discuss things. Closing this.

**Comment by govindowlok0** [comment]
sorry for this i'm so exited to forgot write a details 

I have solutions - -----GPAY is working When you register bank UPI ID like --- @dbs , @hdfc ok thanks me leter

**Comment by lazydevpro** [comment]
@govindowlok0 can you add a bit more detail, what are you trying to say?
