### ISSUE TITLE
Payment failed with the message You're trying to send money to a blocked UPI ID

### ISSUE THREAD

**Issue by bkubes** [PatilShreyas/EasyUpiPayment-Android#131]
Greetings, Shreyas!
We're having problems transferring money right now; we get a notice that says "Payment failed." You're trying to send money to a blocked UPI ID; please try with another UPI ID. Could you double-check it?

Note: I'm just attempting to transfer funds to business accounts only.

**Comment by bkubes** [comment]
Issue seems to be with the UPI Id, after re generating with other bank now we are able to proceed without any issues.

**Comment by turbosoft-anandc** [comment]
plz tell how you solve this issue ..plz elaborate the solution
