### ISSUE TITLE
[HIRING OFFER] Carnegie Mellon AI founder

### ISSUE THREAD

**Issue by akshhack** [PatilShreyas/EasyUpiPayment-Android#176]
Hey Shreyas, 

Amazing profile. Would love to chat. We're a team of deep AI ML engineers looking for a solid full-stack engineer. Send me an email to ack@usecamb.ai if you're interested

**Comment by PatilShreyas** [comment]
Thanks but this is an inappropriate place for this discussion. Also, not looking for a change at the moment.
