### ISSUE TITLE
there is one issue when i am using BHIM for payment and if i cancel it intentionally the app crashes.. 

### ISSUE THREAD

**Issue by suryabhairaj** [PatilShreyas/EasyUpiPayment-Android#21]
this was the error message (shown in the image 
![Screenshot (228)](https://user-images.githubusercontent.com/31375031/72224619-66916480-35a2-11ea-81ac-811794dc3e92.png)
)

**Comment by PatilShreyas** [comment]
Thanks for reporting this. I'll look into it and will fix is asap.

**Comment by suryabhairaj** [comment]
thanks for the reply ..
i will be waiting for the fix!!

**Comment by suryabhairaj** [comment]
Did you got it ??

**Comment by suryabhairaj** [comment]
Is it fixed ??

**Comment by PatilShreyas** [comment]
Not yet. Can you please provide more details about this? How to produce
this error?

**Comment by suryabhairaj** [comment]
try using BHIM app for making payment. After the portal of bhim app is open and ready to pay .. then press back button app crashes  :{(

**Comment by PatilShreyas** [comment]
I've tried it. But I didn't got error.

**Comment by suryabhairaj** [comment]
in my case error is coming as you can see the image ..
is there any other information you want me give ??
sorry i was busy on some other project.. didn't saw your reply ..
hope you are on some date (14 Feb) ;)
you can reply tomorrow.. fine by me..

**Comment by PatilShreyas** [comment]
Oh okay! I just observed that error. Some UPI apps don't send response back
to caller that's why it's happening. I'll solve this in upcoming version.
Thanks for filling this issue. It will help me a lot to create better!

**Comment by suryabhairaj** [comment]
thanks !!

**Comment by PatilShreyas** [comment]
This issue is fixed and implemented in `v2.1`. Thanks!

**Comment by jdsmart53** [comment]
try using BHIM app for making payment. After the portal of bhim app is open and ready to pay also payment successfull but  then response is onTransactionFailed and onTransactionCancelled :{(
But same operation works fine for the case other than BHIM App.
