### ISSUE TITLE
isDefaultAppExist is not implemented in source ?

### ISSUE THREAD

**Issue by signalarun** [PatilShreyas/EasyUpiPayment-Android#22]
The method isDefaultAppExist is not found in the library module code. Found when the code was recompiled for supporting minSdkDependency 14.

**Comment by PatilShreyas** [comment]
Can you describe exact problem? Please provide description.

**Comment by Vivekburada** [comment]
The method isDefaultAppExist is not found in the source code. Your library is a just a blind pipeline for who directly implement from Repository. 

Making something OpenSource means giving full right to the codebase for the developer.

I see some things are purposely taken out carefully. 

Hope I was not wrong!!

**Comment by PatilShreyas** [comment]
Hi @Vivekburada, just reviewed your query and found that it's my mistake. I forgot to push latest code in this repository. Now I've pushed code and you can see `isDefaultAppExist()` method in code.
Thank you for your awareness and sorry for that.
I'm closing that issue.
