### ISSUE TITLE
PhonePay and GooglePay not working

### ISSUE THREAD

**Issue by monikamishra-54** [PatilShreyas/EasyUpiPayment-Android#23]
In response showing null in approvalRefNo and 00 in response code.
Here is Log Details
TransactionDetails: transactionId:T1579696281289, responseCode:00, transactionRefId:T1579696281289, approvalRefNo:null, status:Success

While Paytym is working.

**Comment by PatilShreyas** [comment]
This problem isn't associated with this library. It's that UPI apps not providing response as per NPCI guidelines. Still, you're getting status confirmation and it's sufficient. Thank you
