### ISSUE TITLE
[Request on documentation]

### ISSUE THREAD

**Issue by Vivekburada** [PatilShreyas/EasyUpiPayment-Android#27]
Hi Shreyas, 

Greeting!

It's a kind request that whenever you update the package please let me know what all new features have been done. 

Thank you.

**Comment by PatilShreyas** [comment]
Thanks @Vivekburada for this. But you're talking about which feature? Please describe in brief.

**Comment by PatilShreyas** [comment]
It's still not clarified. So I'm closing this issue.
