### ISSUE TITLE
Google pay not showing in payment options

### ISSUE THREAD

**Issue by RohinBhat** [PatilShreyas/EasyUpiPayment-Android#28]
When I click pay, the options show up. But, there is no option for paying through Google Pay. 
![IMG_20200322_142737](https://user-images.githubusercontent.com/56036924/77246040-63bd8a80-6c49-11ea-9a9f-77588211cbef.jpg)

**Comment by PatilShreyas** [comment]
Is Google Pay app installed on your device? If it is then please check it
is setup or not and then try again.

**Comment by RohinBhat** [comment]
Google pay is both installed and setup. I even use it myself.

**Comment by PatilShreyas** [comment]
What's result when manually choosing Google Pay from options?

**Comment by PatilShreyas** [comment]
Open Google Pay app once and try it after. I'm closing this issue.
