### ISSUE TITLE
Question: Response code U29-RA for failure of a transaction

### ISSUE THREAD

**Issue by samair** [PatilShreyas/EasyUpiPayment-Android#29]
Any idea of response code U29-RA for a failed transaction.
If there is UPI api guide, please point me towards it.

**Comment by PatilShreyas** [comment]
Here is the link: https://www.npci.org.in/sites/default/files/UPI%20Procedural%20Guidelines_29oct19.pdf

**Comment by samair** [comment]
Thanks for document, though i found out later response codes are specific to UPI apps. So google pay has its own meaning, phonepe would have some other codes.
If anyone faces similar response codes on failure
U29-RA on google pay means the transaction ID has already been used.

**Comment by PatilShreyas** [comment]
Then you'll have to generate your own unique transaction ID
