### ISSUE TITLE
[BUG?] Missing Mpin field 

### ISSUE THREAD

**Issue by Akshshr** [PatilShreyas/EasyUpiPayment-Android#30]
Hey cool library, but looks like payments aren't going through at all, I keep seeing a 'missing m-pin' toast.

Any clue where this is coming from and how to fix it?

**Comment by PatilShreyas** [comment]
Hi Akash, can you give brief description of problem you're facing?

**Comment by Akshshr** [comment]
so after picking a UPI enabled application, and hit "confirm" on google Pay, I get an error toast which says "Mpin missing"

**Comment by PatilShreyas** [comment]
Have you set up your profile on UPI app (Google pay) account on your phone?
You might not have set up MPIN in your Google Pay. Try this!

**Comment by Akshshr** [comment]
Yes google pay works just as expected otherwise, I can send and recieve money. Umm there is no such thing as MPin in Google Pay..as far as I can tell

**Comment by PatilShreyas** [comment]
Okay. So this problem isn't associated with this library. It's showing in Google Pay app then it might me another problem. I'm closing this issue now.

**Comment by Akshshr** [comment]
Hey again, so I have this Mpin thing set up now. But still seeing and issue, when I open the payment page (Google pay) using the code, after hitting 'Pay' then -> UPI Pin -> I go back to Pay page...it never seems to proceed to a confirmation, then trigging the onCompleted and onFailed callbacks..and since there is no error being thrown, I have no idea what the issue is..any clue? @PatilShreyas

**Comment by PatilShreyas** [comment]
Can you check logcat? Or try this with another UPI app.

**Comment by Akshshr** [comment]
Hm logs don't show much. Trying this out with other apps. 
Meanwhile, setPayeeVpa(), the VPA here, can that be app-specific? 
At Google Pay its:
myname-1@oksbi


At Paytm its 
mynumber@upi

with the rest of the UPI apps its something else...does the VPA have to be consistent with each app? Or is there a generic VPA for each person?

**Comment by PatilShreyas** [comment]
VPA can be anything but it should exist. You can transfer money inter UPI
apps too.

**Comment by Akshshr** [comment]
I have that covered, so VPA can be of any app but how does google pay know PAYTMs VPA then? **myname@okSbi** which is my VPA with Google, and paying through Google pay still fails clearly.

**Comment by PatilShreyas** [comment]
Yes, it's centralized system. It's payment interface. VPA is your unique
address. That's why you can pay to any app from any app.

**Comment by Akshshr** [comment]
yeah but how do we fix this? It looks

 like its a deeper issue.
Now the payment straight up fails..doesn't even open the google pay app

![Uploading Screenshot_20200518-212852.png…]()

**Comment by Akshshr** [comment]
Okay double-checked with the "Standard" way to pay using the same fields and it works, It looks like the implementation doesn't work buddy @PatilShreyas. 
I suggest opening this thread as a #BUG

**Comment by PatilShreyas** [comment]
Yes we can reopen this but root of cause should be known. I've tested this
too my side and no errors are coming. Still, you can reopen this.

**Comment by PatilShreyas** [comment]
> yeah but how do we fix this? It looks
> 
>  like its a deeper issue.
> Now the payment straight up fails..doesn't even open the google pay app
> 
> ![Screenshot_20200518-212852](https://user-images.githubusercontent.com/11215286/82234737-6be72d00-994f-11ea-89c2-1dec85a7bd45.png)
> 
> 

And this issue is associated with UPI apps not library. I think UPI network problem is going on due to lockdown in these days.

**Comment by Akshshr** [comment]
Unable to reopen it :) 
Yeah the UPI apps are far from stable.

**Comment by PatilShreyas** [comment]
Okay
