### ISSUE TITLE
TransactionID mismatch

### ISSUE THREAD

**Issue by umangburman** [PatilShreyas/EasyUpiPayment-Android#32]
Hi,

Thanks for writting this library. It's really very good and useful.

The issue that I'm facing is with the TransactionID.

When the transaction is executed, I'm able to get the TransactionId which I provide, but I need the particular app's Transaction ID.

Example: my transid = ED765T but Phonepe's is = PMR45365467575

So here, I'm getting "ED765T" But I need "PMR45365467575"

Note: getApprovalRefNo() always returns null.

Please help with this

**Comment by PatilShreyas** [comment]
Yeah. This problem is associated with PhonePe transactions from years. PhonePe does not send correct transaction ID. Hope they'll fix it soon.
