### ISSUE TITLE
[BUG/FEATURE REQUEST] GET AMOUNT SEND 

### ISSUE THREAD

**Issue by itshiteshverma** [PatilShreyas/EasyUpiPayment-Android#34]
Thing is that the user might change the UPI Amount when the UPI App is opened [In case of Paytm]. Is there any way to get the Actual Amount Send in the onTransactionComplete or onSuccess ???

**Comment by PatilShreyas** [comment]
@itshiteshverma Good suggestion! Currently it doesn't support this but in next version I'll implement it. Thanks for this!

**Comment by PatilShreyas** [comment]
Thanks @itshiteshverma. It's implemented and available in `v2.2`.

**Comment by itshiteshverma** [comment]
Thank you for your response
