### ISSUE TITLE
Need UTR number  (unique transaction reference) number on Transaction Success

### ISSUE THREAD

**Issue by shankar7545** [PatilShreyas/EasyUpiPayment-Android#46]
For every UPI transaction , there will be a UTR transaction numbers. It will be useful to verify the transaction from User. I can't see this option anywhere, if its already exists then please let me know how to utilize it.

**Comment by PatilShreyas** [comment]
Currently, only transaction ID and transaction reference ID are provided by UPI apps whenever payment is done. These guidelines are prepared by NPCI. So we can't go beyond that.

**Comment by shankar7545** [comment]
oh Yeah , but i got some sourcecodes for upi payments. using them i can get UTR number onTransactionSuccess.

For better Understanding i created an application and uploaded the codes to github.
Here is the link 
https://github.com/shankar7545/upiPayment.git

and apk link

https://github.com/shankar7545/upiPayment/blob/master/app-debug.apk

I recently started learning android and i have no knowledge about creating a android dependency . And i like EasyUpiPayment-Android so much and its easier to use .

so if u dont mind, please go through my codes and add the UTR number fetching feature to  EasyUpiPayment-Android.

**Comment by PatilShreyas** [comment]
I got your point. But the term you said "UTR" is actually a `approvalRefNo` which is already provided by this library. I saw your code which is also going same. 

See this: https://patilshreyas.github.io/EasyUpiPayment-Android/#/pages/transaction-details

**Comment by shankar7545** [comment]
thank you , my issue is solved

**Comment by shankar7545** [comment]
I tried to get approvalRefNo but it always returns null.

I tried with phonepe and gpay.

Even with the demo app provied in this library. It returned null

**Comment by PatilShreyas** [comment]
Yes, returning that value depends on UPI app. We're collecting it as per NPCI rules as you can see here: https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf

In your code, you're assuming UTR number as ***ApprovalRefNo*** or ***txnRef***.

**Comment by shankar7545** [comment]
But the codes i referred can fetch the UTR number as txnRef  , and using EasyUPI Payment (approvalRefNo) it is returning null .

Anyway the library is of great help and very minimal code.

**Comment by PatilShreyas** [comment]
Thanks. If you wang txnRef then it's also available here. You can retrieve
it from transaction details. We can't control on response of UPI apps which
actually performs transaction. All here implemented according to NPCI
guidelines. Nothing other than that.

**Comment by PatilShreyas** [comment]
I hope this query is resolved now. Can I close this issue? @shankar7545

**Comment by shankar7545** [comment]
Yes sure
