### ISSUE TITLE
I using this code but thair are show you can not make upi payment can you help me please

### ISSUE THREAD

**Issue by govindowlok0** [PatilShreyas/EasyUpiPayment-Android#55]
Write information about Bug/Feature Request here

**Comment by PatilShreyas** [comment]
Can you please describe the problem you're facing?

**Comment by govindowlok0** [comment]
see this url of phonepay scrren shot
https://ibb.co/bWnm79q

**Comment by govindowlok0** [comment]
also when i try i face this issue see this image url 
https://ibb.co/Wc1ddjV

**Comment by PatilShreyas** [comment]
I saw this, this problem is associated with your UPI profile and Bank account. Since it's not associated with this library, closing this issue.

**Comment by govindowlok0** [comment]
not bank side issue sir i have try 5 different upi  id

**Comment by govindowlok0** [comment]
i have install your demo aap and try to send suing bhim and paytm i face same issue please solve it thankyou

**Comment by govindowlok0** [comment]
Please help me sir i use this library last 5 month for collecting amount for user
