### ISSUE TITLE
TRANSACTION via Google Pay & PhonePe not working

### ISSUE THREAD

**Issue by SukarnaSil** [PatilShreyas/EasyUpiPayment-Android#62]
I am trying to make payments via Google Pay, PhonePe & Paytm. The payments via Google Pay & PhonePe are getting failed!. 

In Google Pay, although the transaction limit is not reached, it is showing limit reached.
In PhonePe, its showing technical errors.

Now, while I am trying to do the payments via GPay or PhonePe apps, there is no such problem.

PLease guide me!

**Comment by Chhokra** [comment]
Yes we're facing this issue as well

**Comment by govindowlok0** [comment]
i'm also facing this issue last 2 day please help me

**Comment by govindowlok0** [comment]
> I am trying to make payments via Google Pay, PhonePe & Paytm. The payments via Google Pay & PhonePe are getting failed!.
> 
> In Google Pay, although the transaction limit is not reached, it is showing limit reached.
> In PhonePe, its showing technical errors.
> 
> Now, while I am trying to do the payments via GPay or PhonePe apps, there is no such problem.
> 
> PLease guide me!

same issue facing lst 2 days i have try 5 library  to upi intent not getting error

**Comment by PatilShreyas** [comment]
Hi, I verified this problem and found that Google Pay's Intent Payment isn't working. They'll fix it at their end. Since this issue isn't related to this library, I'm closing this issue. Thanks!
