### ISSUE TITLE
[BUG/FEATURE REQUEST] TITLE HERE

### ISSUE THREAD

**Issue by govindowlok0** [PatilShreyas/EasyUpiPayment-Android#64]
I am trying to make payments via Google Pay, PhonePe & Paytm. The payments via Google Pay & PhonePe are getting failed!.

In Google Pay, although the transaction limit is not reached, it is showing limit reached.
In PhonePe, its showing technical errors.

Now, while I am trying to do the payments via GPay or PhonePe apps, there is no such problem.

PLease guide me!

**Comment by PatilShreyas** [comment]
Hi, I verified this problem and found that Google Pay's Intent Payment isn't working. They'll fix it at their end. Since this issue isn't related to this library, I'm closing this issue. Thanks!
