### ISSUE TITLE
Getting Payment failed message

### ISSUE THREAD

**Issue by venkatbatchu81** [PatilShreyas/EasyUpiPayment-Android#65]
Hi Shreyas,

Thanks for this wonderful library, I am getting Payment failed "You've exceeded the maximum transaction amount set by your bank" after integrating with this, but i am able to make the payments without any issues using google payment app, could you help me to guide here. 

Please view the snapshot for reference https://ibb.co/q0DSGtY

**Comment by PatilShreyas** [comment]
Hi, I verified this problem and found that Google Pay's Intent Payment isn't working. They'll fix it at their end. Since this issue isn't related to this library, I'm closing this issue. Thanks!

**Comment by venkatbatchu81** [comment]
Thanks Shreyas for the reply

Could you share any info from google if you had any stating that they are
working on this to fix issue,.

Thanks,
Venkat Batchu

**Comment by PatilShreyas** [comment]
I'll surely post updates if I got any

**Comment by venkatbatchu81** [comment]
Thanks Shreyas, Do you have any library for iOS Apps as well similar to
this awesome library.

Regards,
Venkat Batchu

**Comment by PatilShreyas** [comment]
Currently there's no such library for iOS which directly communicates with UPI apps

**Comment by sz32** [comment]
Yes I'm also getting issue as well as Paytm and google pay also

**Comment by iroidzeel** [comment]
Today I contacted to Google pay customer service and they said they didnt have any issues from their side I must be from the developer side

**Comment by Chhokra** [comment]
> Today I contacted to Google pay customer service and they said they didnt have any issues from their side. the issue must be from the developer side

Yeah this happened to me too. @PatilShreyas , who did you talk to on Google's side? They redirected me to sign up on  Google pay for business program
