### ISSUE TITLE
onTransactionCompleted is not getting called after successful payment although onTransactionSuccess is.

### ISSUE THREAD

**Issue by suryabhairaj** [PatilShreyas/EasyUpiPayment-Android#7]
onTransactionCompleted  returns the transaction details which i need . thats why onTransactionCompleted is important for me to get called. but it is not getting called.
please help.

**Comment by PatilShreyas** [comment]
What's process you're doing? Can you show code? What's happening?

**Comment by suryabhairaj** [comment]
easyUpiPayment = new EasyUpiPayment.Builder()
                .with(Authosized_Product.this)
                .setPayeeVpa(companyData.getUpiId())
                .setPayeeName(companyData.getName())
                .setTransactionId(s)
                .setTransactionRefId(s+"1")
                .setDescription(getString(R.string.company_name)+" Product Name : "+productData.getPname())
                .setAmount(String.valueOf(Double.valueOf(productData.getCost())))
                .build();
        easyUpiPayment.setPaymentStatusListener(this);
        easyUpiPayment.startPayment();



@Override
    public void onTransactionCompleted(TransactionDetails transactionDetails) {
        finalTrans.setUpiId(transactionDetails.getTransactionId());
        Log.e("trans data","trans id = "+transactionDetails.getTransactionId()+"  Refrence id "+transactionDetails.getTransactionRefId()+"  refAprovalRefNo = "+transactionDetails.getApprovalRefNo()+" Status Code = "+transactionDetails.getStatus());
//        new TransectionComplete().execute("http://"+Main.getIp()+"/Identify/checker/RegisterTransaction",new Gson().toJson(finalTrans));
    }


public void onTransactionSuccess() {
        watingAlert.dismiss();
        finalTrans.setSuccess(true);
        Toast.makeText(Authosized_Product.this,"Payment Successful !!",Toast.LENGTH_LONG).show();
       //line to make the registration to the database that payment is successful  
        new TransectionComplete().execute("http://"+Main.getIp()+"/Identify/checker/RegisterTransaction",new Gson().toJson(finalTrans));
    }

onTransectionSuccess is successfully running and payment is also successfully completing . but this onTransectionComplete is not running from where the most importent data will come . i.e the TransectionID. 
please help me how to resolve this issue..

**Comment by PatilShreyas** [comment]
Oh! Okay. Can you please try other UPI app so that we can rectify exact
problem?

**Comment by suryabhairaj** [comment]
i had used phonepe .. somthing same was occuring in case of paytm . according to you this code is perfectly fine??

**Comment by PatilShreyas** [comment]
Yeah. Code is perfect

**Comment by PatilShreyas** [comment]
I tested it my side and everything is fine. I'll suggest to refer demo app
code.

**Comment by suryabhairaj** [comment]
easyUpiPayment = new EasyUpiPayment.Builder()
.with(Authosized_Product.this)
.setPayeeVpa(companyData.getUpiId())
.setPayeeName(companyData.getName())
.setTransactionId(s)
.setTransactionRefId(s+"1")
.setDescription(getString(R.string.company_name)+" Product Name : "+productData.getPname())
.setAmount(String.valueOf(Double.valueOf(productData.getCost())))
.build();
easyUpiPayment.setPaymentStatusListener(this);
easyUpiPayment.startPayment();

There might be error in this.. s= 835363829 for one case.

**Comment by PatilShreyas** [comment]
Hmm. What's this variable s? Try passing System.currentTimeInMillis() to ID.

**Comment by suryabhairaj** [comment]
yes it is working after changing the value of s.. System.currentTimeInMillis() is working .. but what should 
 be actually put inside the transaction id ? and the TransactionRefId . and why is it working in this case? is there some limit on the length on the string 's'(in my case) .

**Comment by PatilShreyas** [comment]
Maybe your variable s isn't perfect to be transaction id. No problem. Use
your custom code concatenated with currentTimeStamp().

**Comment by suryabhairaj** [comment]
okey thanks a lot ... man

**Comment by PatilShreyas** [comment]
Anytime!

**Comment by suryabhairaj** [comment]
and one more this ..
what if the payment is from the bank is taking much time than usual . and what if the bank server is down . have you handled that

**Comment by PatilShreyas** [comment]
Then it'll call onTransactionPending().

**Comment by suryabhairaj** [comment]
in that case what should we do to insure consistency .

**Comment by PatilShreyas** [comment]
In that case, we can't do anything, because we're not getting anything from
server. All we have to do it manually then.

**Comment by suryabhairaj** [comment]
what if payment is successful after 2-3 days ? if there a way to check from on the server side that is the payment is successful or not?

**Comment by PatilShreyas** [comment]
No. We can't check it.

**Comment by suryabhairaj** [comment]
okey ... again.. thanks a lot man..

**Comment by suryabhairaj** [comment]
sorry to bother you again .. onTransactionPending() is not there in your interface . and neither in your documentation.

**Comment by PatilShreyas** [comment]
@suryabhairaj Sorry for the late reply. It's my mistake. callback `onTransactionSubmitted()` is called when it's pending.

**Comment by PatilShreyas** [comment]
I think issue is resolved. So I'm closing issue. If you found anything, you can reopen it.

**Comment by Gammaprince** [comment]
sir your library invoking wrong callback it says phone doesn't have any upi app , but there are upi apps installed in my phone 
what is the solution ? why is it behaving so different?
If you could give your precious time please help me out
