### ISSUE TITLE
Interactive demo app for Payment

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/EasyUpiPayment-Android#8]
Currently, a demo app of repo included static information hardcoded and directly passed to `EasyUpiPayment`. It'll be useful for testing if developers can test the library using demo APK. 

**Requirement:**
Add `EditText` fields to take user inputs such as Transaction ID, payee name, payee vpa, etc mandatory details and after clicking on button, these details should passed to `EasyUpiPayment` object. That's it. 
and one more important thing - ***Keep It Material***
PRs are welcome.

**Comment by ranjsa** [comment]
@PatilShreyas  I want to work on it .

**Comment by PatilShreyas** [comment]
Feeling glad that you want to work on this . Just fork this repo, work on that and open PR against demo-app-update .

**Comment by Lezzma** [comment]
Done awaiting approval.

**Comment by chiragdivinetechs** [comment]
![WhatsApp Image 2019-12-06 at 1 15 56 PM](https://user-images.githubusercontent.com/43512427/70368568-4bac4000-18d2-11ea-8fcd-2a9b9b900408.jpeg)

i always see Duplicate transacation received error. what is ussue ?

**Comment by PatilShreyas** [comment]
Hi @chiragdivinetechs, this is happening because you are passing Transaction ID and Ref ID same every time. Generate it dynamically instead of hardcoded string.
