### ISSUE TITLE
[Issue] Query about the new release

### ISSUE THREAD

**Issue by Chhokra** [PatilShreyas/EasyUpiPayment-Android#80]
Write information about Bug/Feature Request here
So with the new update it isn't possible for us to pay to non-merchant accounts. But my doubt is does the user(us) need to have a merchant/business account as well? Or can we the user have a normal account and pay any merchant account?

**Comment by prvnsam** [comment]
yes am also have this doubt please confirm

**Comment by PatilShreyas** [comment]
I can only say, merchant code field is mandatory but we can keep it empty! When I personally tried, payment is only successful when payee is having business/merchant account. It's not successful for general UPI account. I hope this helps.
