### ISSUE TITLE
[BUG] Sample APK not working on my Redmi note 9 pro max device

### ISSUE THREAD

**Issue by satish6155** [PatilShreyas/EasyUpiPayment-Android#83]
Sample APK not working on my Redmi note 9 pro max device, tried PhonePay and GPay, please check.

**Comment by satish6155** [comment]
I think your code has stopped working because some changes has been introduced by NPCI in deep linking of UPI, please try running your app once and check whether it is working or not.

**Comment by PatilShreyas** [comment]
I cross checked using PhonePe and WhatsApp UPI and it's perfectly working fine at my end.

Maybe issue is something related to values you're putting there.

**Comment by PatilShreyas** [comment]
So I think it's not an issue so closing this. Still you can discuss here.

**Comment by satish6155** [comment]
![Screenshot_2020-12-17-21-10-57-815_com example easyupipayment](https://user-images.githubusercontent.com/47608162/102509687-d3fc1e00-40ac-11eb-97d8-697ba3fd5804.jpg)
![Screenshot_2020-12-17-21-11-28-612_com example easyupipayment](https://user-images.githubusercontent.com/47608162/102509693-d6f70e80-40ac-11eb-8a9b-f73738ef1d92.jpg)

**Comment by satish6155** [comment]
Check screenshots in above comment.

**Comment by PatilShreyas** [comment]
Try with other apps

**Comment by satish6155** [comment]
Tried PhonePay also.
