### ISSUE TITLE
[BUG/FEATURE REQUEST] TITLE HERE

### ISSUE THREAD

**Issue by shyam123456789** [PatilShreyas/EasyUpiPayment-Android#85]
Write information about Bug/Feature Request here
![WhatsApp_Image](https://user-images.githubusercontent.com/30208709/103367060-26e0c700-4aea-11eb-8150-4316d4c1f7ff.jpeg)

**Comment by PatilShreyas** [comment]
Can't get it. Please describe the exact issue. Feel free to reopen.
