### ISSUE TITLE
[BUG] Getting error: Maximum transaction amount limit exceeded for all transactions

### ISSUE THREAD

**Issue by sunnyagarwal008** [PatilShreyas/EasyUpiPayment-Android#87]
Hi,

This was working perfectly, but now I am getting "Maximum transaction amount limit exceeded" for any transaction amount (tried from 1-100) and for all apps (tested on PayTm, PhonePe, GooglePe).

Are you aware of any changes done from UPI end which might have caused this?

**Comment by PatilShreyas** [comment]
It needs merchant code now. It'll work if you provide it.

**Comment by sunnyagarwal008** [comment]
But that means it won't work for individual upi accounts who don't have merchant codes?

**Comment by PatilShreyas** [comment]
Yes it won't. Please read docs carefully.
