### ISSUE TITLE
[BUG] Payments not completed 

### ISSUE THREAD

**Issue by anirudh3997** [PatilShreyas/EasyUpiPayment-Android#91]
As given in the documentation have provided all the details but payment fails 
1. google pay shows error "You have exceeded maximum transaction amount set by your bank" while other transaction to other places works just fine.
2. phonepay shows error " Could not initiate transaction. Please try again.."
` easyUpiPayment = EasyUpiPayment(this){
            this.payeeVpa = "vpa@sbi"
            this.payeeName = "name"
            this.payeeMerchantCode = "dummy_merchant_code"
            this.transactionId = "dummy_transaction_id"
            this.transactionRefId = "dummy_ref_id"
            this.description = "descripiton"
            this.amount = "10.00"
        }
  easyUpiPayment.startPayment()
 easyUpiPayment.setPaymentStatusListener(this)`

**Comment by venkataseshaiahudatha** [comment]
I'm also getting same error. Can someone please help on the same. I'm trying to send money to personal UPI account and it is failing always with above mentioned errors.

**Comment by fastcash-ops** [comment]
Currently it works only with merchant UPI ids

**Comment by sandydebug** [comment]
With merchant UPI id also it is showing error .
<Payment failed , something went wrong(UPVD)>

**Comment by fastcash-ops** [comment]
Pass empty string in merchat code (mc) while you initiate intent

**Comment by sandydebug** [comment]
Yes , leaving the merchant code parameter blank works for upi payment only if you have passed a business upi id.

**Comment by fastcash-ops** [comment]
Anyone please tell me is there any limit on number on transactions or amount limit for this type of integration ?

**Comment by sandydebug** [comment]
No there is no limitations on app initiated payment , but there might be limitations set by bank like monthly amount of transaction or daily number of transactions . Vary from bank to bank.

**Comment by harryAggarwal** [comment]
Iam still facing the issue something went wrong after pass empty string in merchant code .

**Comment by harryAggarwal** [comment]
Some times its showing : 

this transection may be risky. For your Safety its can't be completed at this time

**Comment by venkataseshaiahudatha** [comment]
> Currently it works only with merchant UPI ids

Is it possible to use this library to send money from the Merchant account to other vice-versa? I have a requirement to redeem cash from App. Where the merchant has to send back money to normal users. I observed few things here 1)  I'm not able to see the Business app in filtered payment apps.2) Is it possible to send money from merchant business app to normal users using a UPI intent-based approach.

**Comment by PatilShreyas** [comment]
As mentioned in the [docs](https://patilshreyas.github.io/EasyUpiPayment-Android/#/?id=introduction) check whether you're performing transactions against a valid merchant/business account.

**Comment by amitimg29** [comment]
@PatilShreyas Hello, I'm facing same issue, with merchant VPA and merchant id.
