### ISSUE TITLE
Few customers are facing issues

### ISSUE THREAD

**Issue by bkubes** [PatilShreyas/EasyUpiPayment-Android#96]
Hi Shreyas,

Could you please help me to look into this issue?

Few customers are able to do the transaction and few customers are not and it is not going into Successful transaction-message though amount gets deducted from their account. 

Thanks

**Comment by PatilShreyas** [comment]
Hi @bkubes I think it's a case of transaction being pending. In this case, amount gets deducted from account but status is neither successful or failure. In this case, application should provide payment support to the end users.
