### ISSUE TITLE
GPAY is thowing error message "This transaction may be risky. For your safety. It cant be completed at this time"

### ISSUE THREAD

**Issue by bkubes** [PatilShreyas/EasyUpiPayment-Android#98]
Dear Shreyas,

Out customers are facing issues while paying the money through Gpay and here is the error message "This transaction may be risky. For your safety. It cant be completed at this time".

Could you suggest if we can do anything over here, thanks for your time .

**Comment by ShankarKakumani** [comment]
Yeah, This error is showing in most of the payment apps

**Comment by kiranthati521** [comment]
This transaction may be risky. For your safety. It cant be completed at this time
same issue am also getting how to fix this issue please let me know

**Comment by abhilash-gupta** [comment]
Facing same issue as above, (using Google Pay and merchant UPI ID)
This transaction may be risky. For your safety. It cant be completed at this time

Here's the code:
EasyUpiPayment.Builder builder = new EasyUpiPayment.Builder(this)
                        //.with(PaymentApp.GOOGLE_PAY) // pays specifically with Google pay
                        .setPayeeVpa(upiID)
                        .setPayeeName(upiName)
                        .setPayeeMerchantCode(upiMerchantID)
                        .setTransactionId("F20304050")
                        .setTransactionRefId("F20304050")
                        .setDescription(upiNote)
                        .setAmount(upiAmount);

                EasyUpiPayment easyUpiPayment = builder.build();
                easyUpiPayment.startPayment();

**Comment by rohitanacr7** [comment]
Dear Shreyas,

Out customers are facing issues while paying the money through Gpay and here is the error message "This transaction may be risky. For your safety. It cant be completed at this time".

Could you suggest if we can do anything over here, thanks for your time .

**Comment by PatilShreyas** [comment]
As mentioned in the [docs](https://patilshreyas.github.io/EasyUpiPayment-Android/#/?id=introduction) check whether you're performing transactions against a valid merchant/business account.

**Comment by RandomCatGit** [comment]
This is caused by recent changes to security in UPI transactions to prevent fraud. See https://stackoverflow.com/a/68800878/4697928

**Comment by RilanJayswal** [comment]
> Dear Shreyas,
> 
> Out customers are facing issues while paying the money through Gpay and here is the error message "This transaction may be risky. For your safety. It cant be completed at this time".
> 
> Could you suggest if we can do anything over here, thanks for your time .

**Comment by PatilShreyas** [comment]
Hi, have you tried providing merchant code? Actually updates are happening from NPCI side constantly and they're always trying to tighten the security which is really good.

**Comment by RilanJayswal** [comment]
> Hi, have you tried providing merchant code? Actually updates are happening from NPCI side constantly and they're always trying to tighten the security which is really good.

Yes I try

**Comment by yu783** [comment]
> 

sir can you providing the main activity source code

**Comment by theparmendrasingh** [comment]
> Hi, have you tried providing merchant code? Actually updates are happening from NPCI side constantly and they're always trying to tighten the security which is really good.

Tried providing merchant code.. Still the same error. Please advise ASAP.

**Comment by s1315d** [comment]
Iam also facing the same issue and it was really a mess as accepting or sending payment through gpay is blocked but for other upi apps its working for same bank

When i try to send money to anyone it says

"This transaction is risky for your safety it can't be completed at this time "

When i try to recieve money ut gives other eeror to people

**Comment by vibinernesto** [comment]
Even after providing the merchant code im getting this error. Does it take time to validate merchant code? or do we need to do anything else? please advise

**Comment by prajwalmw** [comment]
Same issue still do we need to verify our merchant account in gpay? If we verify with gpay as well than what about other upi apps? Do we need to verify ourselves in each and every upi app that we need? Also, what docs do we need to verify our merchant account for verified merchant upi id? @PatilShreyas

**Comment by vipulm7** [comment]
> Hi, have you tried providing merchant code? Actually updates are happening from NPCI side constantly and they're always trying to tighten the security which is really good.

Tried providing merchant code but still it's not working. what to do?

**Comment by SaurabhPurohit20** [comment]
Any one found a solution for an error This transaction is risky for your safety it can't be completed at this time.
& limit exceed I used EasyUpiPayment-Android v3.0.3
Tell me solutions if available @ saurabhpurohit20@gmail.com
